#!/usr/bin/env rerun ruby

require "bundler/setup"
require "round_tracker"
require "sinatra"

configure do
  set :views, 'app/views/'
  set :public_folder, 'app/assets'
end

get '/' do
  @all_rounds = RoundTracker::RoundParser.all_rounds
  erb :index
end